#!/usr/bin/env bash
# setup.sh — ONE-COMMAND orchestrator for the vasic-digital optimized tmux
# build & install.
#
# Pipeline (each step gated on the previous):
#   1. Verify container engine (podman or docker) + host libjemalloc.so visible
#      (libjemalloc-dev recommended — install via `sudo bash scripts/install_deps.sh`)
#   2. Containerized build (podman/docker, isolated cgroup, mem_limit=2g)
#   3. Generate tmx wrapper (LD_PRELOAD=jemalloc + oom_score_adj=-500)
#   4. Run verification gate (verify.sh — full 14-test suite)
#   5. ONLY IF GREEN: install ~/.tmux.conf + .bashrc snippet + PATH export
#
# §11.4 invariant: step 5 is GATED by step 4. Failing tests means no PATH export.
# §12.9 invariant: step 2 runs in an isolated container cgroup (host insulated).
#
# Usage: bash scripts/setup.sh             — full pipeline
#        bash scripts/setup.sh --uninstall — remove .bashrc snippet + ~/.tmux.conf
#        bash scripts/setup.sh --rebuild   — force re-run of containerized build
#        bash scripts/setup.sh --build-only — stop after step 2 (no install)
#        bash scripts/setup.sh --verify-only — stop after step 4 (no install)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ── arg parsing ─────────────────────────────────────────────────────────────
MODE="install"
while [ $# -gt 0 ]; do
    case "$1" in
        --uninstall)   MODE="uninstall" ;;
        --rebuild)     MODE="rebuild" ;;
        --build-only)  MODE="build-only" ;;
        --verify-only) MODE="verify-only" ;;
        --help|-h)
            sed -n '1,/^# Usage/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown arg: $1"; exit 2 ;;
    esac
    shift
done

# Portable in-place range delete between two marker lines.
# `sed -i` works differently on GNU (Linux) and BSD (macOS) — the BSD form
# requires `-i ''`. Using perl avoids the divergence; flip-flop `..` matches
# lines between the start and end markers inclusive, and `print unless` keeps
# everything outside that range. This is the only operation that touches
# the operator's ~/.bashrc directly.
_strip_bashrc_snippet() {
    local file="$1"
    [ -f "$file" ] || return 0
    perl -i -ne 'print unless /^# ─── vasic-digital optimized tmux/ .. /^# ─── end vasic-digital optimized tmux/' "$file"
}

# ── uninstall path ──────────────────────────────────────────────────────────
if [ "$MODE" = "uninstall" ]; then
    echo "[setup] uninstalling…"
    for rc in ~/.bashrc ~/.zshrc; do
        if [ -f "$rc" ] && grep -q '─── vasic-digital optimized tmux' "$rc" 2>/dev/null; then
            _strip_bashrc_snippet "$rc"
            echo "  ✓ removed snippet from $rc"
        fi
    done
    if [ -f ~/.tmux.conf ] && grep -q 'vasic-digital optimized tmux configuration' ~/.tmux.conf; then
        rm -f ~/.tmux.conf
        echo "  ✓ removed ~/.tmux.conf (was generated by setup.sh)"
    fi
    rm -f scripts/tmx
    echo "  ✓ removed wrapper scripts/tmx"
    echo "  Note: tmux/build/ kept; remove with 'rm -rf tmux/build' if desired"
    exit 0
fi

# ── installation pipeline (NATIVE dual-OS per docs/plans/native-dual-os.md) ──

HOST_OS="$(uname -s)"

# Step 1 — host capability check
echo "[setup] step 1 — host capability check ($HOST_OS)"
case "$HOST_OS" in
    Darwin)
        if ! command -v brew >/dev/null 2>&1; then
            echo "  ✗ Homebrew not installed. Install via:"
            echo "    /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
            exit 3
        fi
        echo "  ✓ Homebrew @ $(brew --prefix)"
        JEMALLOC_DYLIB="$(brew --prefix jemalloc 2>/dev/null)/lib/libjemalloc.dylib"
        if [ -f "$JEMALLOC_DYLIB" ]; then
            JEMALLOC="$JEMALLOC_DYLIB"
            echo "  ✓ jemalloc @ $JEMALLOC"
        else
            JEMALLOC=""
            echo "  ⓘ jemalloc not yet installed — build_native.sh will install it"
        fi
        ;;
    Linux)
        ENGINE=""
        if command -v podman >/dev/null 2>&1; then
            ENGINE="podman"
        elif command -v docker >/dev/null 2>&1; then
            ENGINE="docker"
        fi
        if [ -z "$ENGINE" ] && [ ! -x "$REPO_ROOT/tmux/build/bin/tmux" ]; then
            echo "  ✗ neither podman nor docker installed AND no native build present."
            echo "    Either install a container engine, or install libevent-dev + libjemalloc-dev + build-essential and use build_native.sh."
            exit 3
        fi
        [ -n "$ENGINE" ] && echo "  ✓ container engine: $ENGINE"
        JEMALLOC=""
        for _C in ldconfig /sbin/ldconfig /usr/sbin/ldconfig; do
            command -v "$_C" >/dev/null 2>&1 || continue
            JEMALLOC=$("$_C" -p 2>/dev/null | awk '/libjemalloc\.so\.[0-9]/ {print $NF; exit}' || true)
            [ -n "$JEMALLOC" ] && break
        done
        if [ -z "$JEMALLOC" ]; then
            echo "  ⚠ host libjemalloc.so not visible — wrapper LD_PRELOAD will be inert"
        else
            echo "  ✓ host libjemalloc: $JEMALLOC"
        fi
        ;;
    *)
        echo "  ✗ unsupported OS '$HOST_OS'. Supported: Darwin, Linux."
        exit 3
        ;;
esac

# Step 2 — build the tmux binary natively for this OS
echo ""
echo "[setup] step 2 — native build"
case "$HOST_OS" in
    Darwin)
        TMUX_BIN_ABS="$REPO_ROOT/tmux/build-darwin/bin/tmux"
        if [ "$MODE" = "rebuild" ] || [ ! -x "$TMUX_BIN_ABS" ]; then
            bash scripts/build_native.sh
        else
            echo "  binary already present at $TMUX_BIN_ABS — use --rebuild to force"
        fi
        # Refresh jemalloc path now that brew install ran inside build_native.sh.
        JEMALLOC_DYLIB="$(brew --prefix jemalloc 2>/dev/null)/lib/libjemalloc.dylib"
        if [ -f "$JEMALLOC_DYLIB" ]; then
            JEMALLOC="$JEMALLOC_DYLIB"
        fi
        ;;
    Linux)
        TMUX_BIN_ABS="$REPO_ROOT/tmux/build/bin/tmux"
        if [ "$MODE" = "rebuild" ] || [ ! -x "$TMUX_BIN_ABS" ]; then
            if [ -n "${ENGINE:-}" ]; then
                bash scripts/build_containerized.sh
            else
                bash scripts/build_native.sh
            fi
        else
            echo "  binary already present at $TMUX_BIN_ABS — use --rebuild to force"
        fi
        ;;
esac

if [ "$MODE" = "build-only" ]; then
    echo "[setup] --build-only: stopping after step 2"
    exit 0
fi

# Step 3 — generate the tmx wrapper from tmx.template
echo ""
echo "[setup] step 3 — generating tmx wrapper"
RLIMIT_WRAPPER_ABS="$REPO_ROOT/scripts/tmx-rlimit-wrapper.sh"
sed \
    -e "s|__TMUX_BIN__|$TMUX_BIN_ABS|g" \
    -e "s|__JEMALLOC_PATH__|$JEMALLOC|g" \
    -e "s|__RLIMIT_WRAPPER__|$RLIMIT_WRAPPER_ABS|g" \
    scripts/tmx.template > scripts/tmx
chmod +x scripts/tmx
echo "  ✓ wrote scripts/tmx ($HOST_OS native wrapper, host-process isolation: $(if [ "$HOST_OS" = "Darwin" ]; then echo "POSIX rlimit"; else echo "cgroup-v2 transient scope"; fi))"

# Clean up any legacy files from the previous VM-based architecture so the
# operator doesn't get confused by their presence (no longer used in
# native dual-OS install path).
rm -f scripts/tmx-vm
rm -f scripts/tmx-mac.template.bak 2>/dev/null || true

# Step 3b — build oom_set helper binary (no sudo). Operator can later install
# with `sudo bash scripts/build_oom_set.sh --install` to get full OOM
# protection without the wrapper needing sudo per launch. See §8 of guide.
echo ""
echo "[setup] step 3b — building oom_set helper (Linux only; SKIP on Darwin)"
if [ "$HOST_OS" = "Linux" ] && [ -f scripts/oom_set.c ] && [ -x scripts/build_oom_set.sh ]; then
    bash scripts/build_oom_set.sh 2>&1 | grep -E "wrote|complete" | sed 's/^/  /'
    if [ -x /usr/local/bin/tmx-oom-set ]; then
        echo "  ✓ /usr/local/bin/tmx-oom-set installed (cap_sys_resource+ep) — Test 08 will PASS"
    else
        echo "  ⓘ helper compiled but not installed system-wide. To enable Test 08 PASS:"
        echo "       sudo bash scripts/build_oom_set.sh --install"
    fi
fi

# Step 3c — CodeGraph index bootstrap (per §11.4.77 + §11.4.78). The
# `.codegraph/codegraph.db` artefact is gitignored; per §11.4.77 we have
# a regeneration mechanism declared at `.gitignore-meta/codegraph-db.yaml`
# pointing at `scripts/codegraph_reindex.sh`. Pre-Nezha-fix (2026-05-21)
# setup.sh did NOT actually invoke that script, so fresh clones had no
# DB and test 21 FAILed — the §11.4 PASS-bluff pattern §11.4.77 was
# written to prevent. Now invoked here unconditionally; codegraph_reindex
# is idempotent (init + index on first call, sync on subsequent ones).
echo ""
echo "[setup] step 3c — CodeGraph index bootstrap (§11.4.77 regen mechanism)"
if command -v codegraph >/dev/null 2>&1; then
    if [ -x scripts/codegraph_reindex.sh ]; then
        bash scripts/codegraph_reindex.sh 2>&1 | grep -E "regenerated|node|RED" | sed 's/^/  /'
    else
        echo "  ⓘ scripts/codegraph_reindex.sh not executable — skip §11.4.77 bootstrap"
    fi
else
    echo "  ⓘ codegraph CLI not on PATH — install per §11.4.78 (npm install -g @colbymchenry/codegraph)"
    echo "       Test 21 will FAIL until installed; setup.sh continues so the operator can install + retry."
fi

# Step 4 — verification gate (THE GUARD)
echo ""
echo "[setup] step 4 — verification gate"
# Native dual-OS: the binary is built FOR THIS HOST and verified ON THIS
# HOST. No more VM bridge in the default install flow. verify.sh respects
# $TMUX_BIN env override.
export TMUX_BIN="$TMUX_BIN_ABS"
export WRAPPER="$REPO_ROOT/scripts/tmx"
if ! bash scripts/verify.sh; then
    echo ""
    echo "[setup] ✗ verification RED. Aborting before PATH-export."
    echo "  Per §11.4 anti-bluff covenant, we DO NOT expose unverified binaries."
    exit 4
fi
echo ""
echo "[setup] ✓ verification GREEN — safe to proceed with installation"

if [ "$MODE" = "verify-only" ]; then
    echo "[setup] --verify-only: stopping after step 4. PATH NOT exported."
    exit 0
fi

# Step 5 — install ~/.tmux.conf + .bashrc snippet (gated)
echo ""
echo "[setup] step 5 — installing user config"

if [ -f ~/.tmux.conf ] && ! grep -q 'vasic-digital optimized tmux configuration' ~/.tmux.conf; then
    echo "  ⚠ ~/.tmux.conf exists and is NOT ours — backing up to ~/.tmux.conf.pre-vasic-digital"
    cp -n ~/.tmux.conf ~/.tmux.conf.pre-vasic-digital
fi
cp scripts/tmux.conf.template ~/.tmux.conf
echo "  ✓ ~/.tmux.conf installed"

SNIPPET=$(sed \
    -e "s|__DATE__|$(date '+%Y-%m-%d')|" \
    -e "s|__PROJECT__|$REPO_ROOT|g" \
    scripts/bashrc_snippet.template)

# Append the snippet to whichever shell rc files actually exist. On
# macOS, the default user shell is zsh, so an install that only writes
# to ~/.bashrc would silently fail to put `tmx` on the operator's PATH
# (§1 bluff: install claims tmx is reachable, but in the user's actual
# shell it isn't). Handle both shells; the snippet is bash/zsh-portable.
for rc in ~/.bashrc ~/.zshrc; do
    [ -e "$rc" ] || [ "$rc" = ~/.zshrc -a "$HOST_OS" = "Darwin" ] || continue
    if grep -q '─── vasic-digital optimized tmux' "$rc" 2>/dev/null; then
        _strip_bashrc_snippet "$rc"
    fi
    printf '%s\n' "$SNIPPET" >> "$rc"
    echo "  ✓ snippet appended to $rc"
done

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  vasic-digital optimized tmux installed."
echo "  Open a NEW shell, or source the rc for your shell:"
echo "    bash: source ~/.bashrc"
echo "    zsh:  source ~/.zshrc"
echo ""
echo "  Use 'tmx new|attach|ls|kill' to invoke the verified build."
echo "  The system 'tmux' command stays unchanged and reachable — both"
echo "  coexist side-by-side. PATH gets scripts/ prepended so 'tmx'"
echo "  resolves to this project's wrapper; 'tmux' resolves to whatever"
echo "  was on your PATH before."
if [ "$HOST_OS" = "Darwin" ]; then
    echo ""
    echo "  macOS isolation: each session runs in the macOS host process"
    echo "  tree with kernel-enforced POSIX rlimits applied per session:"
    echo "    • RLIMIT_CPU  (CPU-time cap, ${TMX_CPU_HARD_SEC:-86400} s default)"
    echo "    • RLIMIT_NPROC (per-user process count cap)"
    echo "  ⓘ HONEST GAP: RLIMIT_AS (virtual memory) is NOT enforced by"
    echo "    the XNU kernel for unprivileged processes (returns EINVAL)."
    echo "    Memory containment on macOS requires launchd jobs with"
    echo "    HardResourceLimits plist (root). See docs/guide/README.md §5.6."
    echo "  Full host access: Homebrew, /usr/bin, all system tools reachable."
elif [ "$HOST_OS" = "Linux" ]; then
    echo ""
    echo "  Linux isolation: each session in its own cgroup-v2 transient"
    echo "  scope (tmx-NAME.scope) with MemoryMax / CPUQuota / TasksMax /"
    echo "  Delegate=yes. OOM in one session contained to that scope only."
fi
echo "════════════════════════════════════════════════════════════════"
