#!/usr/bin/env bash
# setup.sh — ONE-COMMAND orchestrator for the vasic-digital optimized tmux
# build & install.
#
# Pipeline (each step gated on the previous):
#   1. Verify container engine (podman or docker) + host libjemalloc.so visible
#      (libjemalloc-dev recommended — install via `sudo bash scripts/install_deps.sh`)
#   2. Containerized build (podman/docker, isolated cgroup, mem_limit=2g)
#   3. Generate tmx wrapper (LD_PRELOAD=jemalloc + oom_score_adj=-500)
#   4. Run verification gate (verify.sh — full 14-test suite)
#   5. ONLY IF GREEN: install ~/.tmux.conf + .bashrc snippet + PATH export
#
# §11.4 invariant: step 5 is GATED by step 4. Failing tests means no PATH export.
# §12.9 invariant: step 2 runs in an isolated container cgroup (host insulated).
#
# Usage: bash scripts/setup.sh             — full pipeline
#        bash scripts/setup.sh --uninstall — remove .bashrc snippet + ~/.tmux.conf
#        bash scripts/setup.sh --rebuild   — force re-run of containerized build
#        bash scripts/setup.sh --build-only — stop after step 2 (no install)
#        bash scripts/setup.sh --verify-only — stop after step 4 (no install)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ── arg parsing ─────────────────────────────────────────────────────────────
MODE="install"
while [ $# -gt 0 ]; do
    case "$1" in
        --uninstall)   MODE="uninstall" ;;
        --rebuild)     MODE="rebuild" ;;
        --build-only)  MODE="build-only" ;;
        --verify-only) MODE="verify-only" ;;
        --help|-h)
            sed -n '1,/^# Usage/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown arg: $1"; exit 2 ;;
    esac
    shift
done

# Portable in-place range delete between two marker lines.
# `sed -i` works differently on GNU (Linux) and BSD (macOS) — the BSD form
# requires `-i ''`. Using perl avoids the divergence; flip-flop `..` matches
# lines between the start and end markers inclusive, and `print unless` keeps
# everything outside that range. This is the only operation that touches
# the operator's ~/.bashrc directly.
_strip_bashrc_snippet() {
    local file="$1"
    [ -f "$file" ] || return 0
    perl -i -ne 'print unless /^# ─── vasic-digital optimized tmux/ .. /^# ─── end vasic-digital optimized tmux/' "$file"
}

# ── uninstall path ──────────────────────────────────────────────────────────
if [ "$MODE" = "uninstall" ]; then
    echo "[setup] uninstalling…"
    if [ -f ~/.bashrc ]; then
        _strip_bashrc_snippet ~/.bashrc
        echo "  ✓ removed snippet from ~/.bashrc"
    fi
    if [ -f ~/.tmux.conf ] && grep -q 'vasic-digital optimized tmux configuration' ~/.tmux.conf; then
        rm -f ~/.tmux.conf
        echo "  ✓ removed ~/.tmux.conf (was generated by setup.sh)"
    fi
    rm -f scripts/tmx
    echo "  ✓ removed wrapper scripts/tmx"
    echo "  Note: tmux/build/ kept; remove with 'rm -rf tmux/build' if desired"
    exit 0
fi

# ── installation pipeline ───────────────────────────────────────────────────

# Step 1 — host capability check (relaxed: containerized build owns most deps)
echo "[setup] step 1 — host capability check"
ENGINE=""
if command -v podman >/dev/null 2>&1; then
    ENGINE="podman"
elif command -v docker >/dev/null 2>&1; then
    ENGINE="docker"
fi
if [ -z "$ENGINE" ]; then
    echo "  ✗ neither podman nor docker installed. Cannot run containerized build."
    echo "    Install one of them via your package manager."
    exit 3
fi
echo "  ✓ container engine: $ENGINE"

JEMALLOC=""
for _C in ldconfig /sbin/ldconfig /usr/sbin/ldconfig; do
    command -v "$_C" >/dev/null 2>&1 || continue
    JEMALLOC=$("$_C" -p 2>/dev/null | awk '/libjemalloc\.so\.[0-9]/ {print $NF; exit}' || true)
    [ -n "$JEMALLOC" ] && break
done
if [ -z "$JEMALLOC" ]; then
    echo "  ⚠ host libjemalloc.so not visible — wrapper LD_PRELOAD will be inert"
    echo "    Tests 03 + 05 will SKIP (jemalloc-dependent)."
    echo "    Recommend: sudo bash scripts/install_deps.sh"
else
    echo "  ✓ host libjemalloc: $JEMALLOC"
fi

# Step 2 — containerized build
echo ""
echo "[setup] step 2 — containerized build"
if [ "$MODE" = "rebuild" ] || [ ! -x tmux/build/bin/tmux ]; then
    bash scripts/build_containerized.sh
else
    echo "  binary already present at tmux/build/bin/tmux — use --rebuild to force"
fi

if [ "$MODE" = "build-only" ]; then
    echo "[setup] --build-only: stopping after step 2"
    exit 0
fi

# Step 3 — generate wrapper
echo ""
echo "[setup] step 3 — generating tmx wrapper"
TMUX_BIN_ABS="$REPO_ROOT/tmux/build/bin/tmux"
sed \
    -e "s|__TMUX_BIN__|$TMUX_BIN_ABS|g" \
    -e "s|__JEMALLOC_PATH__|$JEMALLOC|g" \
    scripts/tmx.template > scripts/tmx
chmod +x scripts/tmx
echo "  ✓ wrote scripts/tmx"

# Step 3b — build oom_set helper binary (no sudo). Operator can later install
# with `sudo bash scripts/build_oom_set.sh --install` to get full OOM
# protection without the wrapper needing sudo per launch. See §8 of guide.
echo ""
echo "[setup] step 3b — building oom_set helper (no install)"
if [ -f scripts/oom_set.c ] && [ -x scripts/build_oom_set.sh ]; then
    bash scripts/build_oom_set.sh 2>&1 | grep -E "wrote|complete" | sed 's/^/  /'
    if [ -x /usr/local/bin/tmx-oom-set ]; then
        echo "  ✓ /usr/local/bin/tmx-oom-set installed (cap_sys_resource+ep) — Test 08 will PASS"
    else
        echo "  ⓘ helper compiled but not installed system-wide. To enable Test 08 PASS:"
        echo "       sudo bash scripts/build_oom_set.sh --install"
    fi
fi

# Step 4 — verification gate (THE GUARD)
echo ""
echo "[setup] step 4 — verification gate"
if ! bash scripts/verify.sh; then
    echo ""
    echo "[setup] ✗ verification RED. Aborting before PATH-export."
    echo "  Per §11.4 anti-bluff covenant, we DO NOT expose unverified binaries."
    exit 4
fi
echo ""
echo "[setup] ✓ verification GREEN — safe to proceed with installation"

if [ "$MODE" = "verify-only" ]; then
    echo "[setup] --verify-only: stopping after step 4. PATH NOT exported."
    exit 0
fi

# Step 5 — install ~/.tmux.conf + .bashrc snippet (gated)
echo ""
echo "[setup] step 5 — installing user config"

if [ -f ~/.tmux.conf ] && ! grep -q 'vasic-digital optimized tmux configuration' ~/.tmux.conf; then
    echo "  ⚠ ~/.tmux.conf exists and is NOT ours — backing up to ~/.tmux.conf.pre-vasic-digital"
    cp -n ~/.tmux.conf ~/.tmux.conf.pre-vasic-digital
fi
cp scripts/tmux.conf.template ~/.tmux.conf
echo "  ✓ ~/.tmux.conf installed"

if grep -q '─── vasic-digital optimized tmux' ~/.bashrc 2>/dev/null; then
    _strip_bashrc_snippet ~/.bashrc
fi
sed \
    -e "s|__DATE__|$(date '+%Y-%m-%d')|" \
    -e "s|__PROJECT__|$REPO_ROOT|g" \
    scripts/bashrc_snippet.template >> ~/.bashrc
echo "  ✓ ~/.bashrc snippet appended"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  vasic-digital optimized tmux installed."
echo "  Open a NEW shell or run: source ~/.bashrc"
echo ""
echo "  Use 'tmx new|attach|ls|kill' to invoke the verified build."
echo "  The system 'tmux' command stays unchanged and reachable — both"
echo "  coexist side-by-side. PATH gets scripts/ prepended so 'tmx'"
echo "  resolves to this project's wrapper; 'tmux' resolves to whatever"
echo "  was on your PATH before."
echo "════════════════════════════════════════════════════════════════"
