#!/usr/bin/env bash
# uninstall.sh — operator-facing entry point for removing the vasic-digital
# tmux installation cleanly. Delegates to `scripts/setup.sh --uninstall`
# which is the single source of truth for what gets removed.
#
# What gets removed (per scripts/setup.sh _do_uninstall):
#   1. The fenced `─── vasic-digital optimized tmux ───` block from
#      ~/.bashrc and ~/.zshrc (whichever exist).
#   2. Any LEGACY pre-v1.0.9 unfenced `if command -v tmx ...; then ... fi`
#      snippet from those rc files (operators who hand-pasted the
#      original snippet).
#   3. ~/.tmux.conf if generated by setup.sh (preserves any pre-existing
#      operator-owned ~/.tmux.conf via a backup created at install time).
#   4. Generated scripts: scripts/tmx (wrapper), scripts/tmx-shell-init.sh
#      (shell init — v1.0.9+), scripts/tmx-state-bin (Go binary — v1.0.9+).
#
# What is PRESERVED by default (must opt-in to remove):
#   - ~/.tmx/ (per-session last-pwd state — operator data per §9
#     zero-risk-data-safety). Pass --purge-state to also remove this.
#   - tmux/build*/ (compiled tmux binary — rebuild costs time). Manual
#     `rm -rf tmux/build*` if desired.
#
# Usage:
#   bash scripts/uninstall.sh                # clean uninstall, preserve ~/.tmx/
#   bash scripts/uninstall.sh --purge-state  # also remove ~/.tmx/ state dir
#
# Documentation: docs/guides/tmx-shell-integration.md §uninstall
# §11.4.18 companion: docs/scripts/uninstall.md
# §11.4.67 POSIX-parseable (sh -n clean).

set -u

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PURGE_STATE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --purge-state) PURGE_STATE=1 ;;
        --help|-h)
            sed -n '1,/^# Usage/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 2 ;;
    esac
    shift
done

# Delegate to setup.sh --uninstall, propagating PURGE_STATE via env.
# This keeps a SINGLE source of truth for what "uninstall" means and
# avoids drift between two implementations.
export PURGE_STATE
exec bash "$REPO_ROOT/scripts/setup.sh" --uninstall
